### ISSUE TITLE
Expand scope of antidote?

### ISSUE THREAD

**Issue by bitskri3g** [nre-learning/antidote-core#207]
I have been asked to investigate what it might cost to create a turnkey virtual learning solution for students in rural areas who don't necessarily have access to top-tier computer scientists and electrical engineers in their school districts.  I know that NRE labs is solely focused on network automation at the moment, but I think there is a lot of excellent work here that could be expanded upon to include many other topics in computer science and electrical engineering (e.g. adding additional protocol support to webssh2 here: https://github.com/billchurch/webssh2/issues/211), etc.  Because antidote also has the self-medicate utility, it becomes an exceptionally valuable solution for people in internet deserts who don't have high-bandwidth connections or reliable access.

I'd love to speak with one/more of the cores about how we might be able to work together and make the nre-learning family even better.

**Comment by Mierdin** [comment]
Since you and I have sync'd up elsewhere, and have also opened this up in greater detail [on the forums](https://discuss.nrelabs.io/t/adding-core-capabilities-to-antidote/313/6) I'm going to close this.
